import "@/sass/globals.sass";
import type { Metadata } from "next";
import { Inter, Teko, Roboto } from "next/font/google";
import { Header } from "@/components";
import { Footer } from "@/components/shared/Footer";
const inter = Inter({ subsets: ["latin"] });
const teko = Teko({ subsets: ["latin"] });
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});
const font = roboto
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
